### ISSUE TITLE
Honoring proxy settings

### ISSUE THREAD

**Issue by Rydekull** [sclorg/s2i-php-container#103]
There is a slight problem with s2i-php when using it behind a proxy with no direct access to the internet. 

Namely: https://github.com/openshift/s2i-php/blob/master/5.6/s2i/bin/assemble#L12

This part specfically (as I understand it) does not honor proxy settings such as http_proxy or HTTP_proxy or its equivalents for different protocols. 

I would ask to simply change it to curl instead to fetch that file since that will follow proxy settings properly.

(The whole discussion about fetching files blindly from the internet is another discussion).

**Comment by Rydekull** [comment]
Similar problems can be found here:
https://github.com/composer/composer/issues/4919#issuecomment-185159029

And another solution to using curl here:
http://stackoverflow.com/questions/1336262/file-get-contents-behind-a-proxy

But I'd say that overcomplicates it since there is a whole range of environment variables that needs to be honored. Curl is the much simpler solution.

**Comment by phracek** [comment]
This is solved by similar approach https://github.com/sclorg/s2i-php-container/blob/master/8.1/s2i/bin/assemble#L34. Feel free to re-open it.
