### ISSUE TITLE
Add NewRelic agent

### ISSUE THREAD

**Issue by spinolacastro** [sclorg/s2i-php-container#115]
I have a patch that add's newrelic agent and ability to config via env vars, would it be acceptable ?

**Comment by bparees** [comment]
defer to SCL team ( @hhorak ), but the general rule is that we're only going to include packages that redhat builds/supports because that's the requirement for things that go into the rhel versions of the images, and we don't want the centos version of the image to fall out of sync w/ the rhel version.

so maybe @hhorak knows if SCL already packages that agent for php or if they are interested in creating a package for it.

**Comment by hhorak** [comment]
> defer to SCL team ( @hhorak ), but the general rule is that we're only going to include packages that redhat builds/supports because that's the requirement for things that go into the rhel versions of the images, and we don't want the centos version of the image to fall out of sync w/ the rhel version.

Exactly, thanks to summarize it so nicely.

> so maybe @hhorak knows if SCL already packages that agent for php or if they are interested in creating a package for it.

Unfortunately, I'm not aware of any request for NewRelic support so far. What is more, I haven't seen source of the php agent on the NewRelic website either, is it available somewhere at all or is it available only in binary form?

Generally, what packages will be available and supported in the RH offerings is driven by customers requests, so the best way to influence what goes in is to contact RH Support.

**Comment by bparees** [comment]
@spinolacastro @hhorak i wonder if it would be worth at least making "ENABLE_NEW_RELIC" a first class config env variable in the assemble script, such that if you specify it, the assemble script would install the new relic bits?  Granted that still means every assemble invocation has to pull that stuff down, but maybe it would make the experience slightly better for users?

We had integrated new relic support in openshift v2, so it seems like this wouldn't be that different from what we did there.

**Comment by spinolacastro** [comment]
That will do, let me do some tests with tar.gz install and get back to you. At least we will have to tweak a little bit some directory permissions.

**Comment by hhorak** [comment]
Making "ENABLE_NEW_RELIC" a first class config env variable in the assemble script seems fine to me, but I'd like to hear @remicollet's opinion as well.

**Comment by phracek** [comment]
We do not have enough requests for this issue. Patch is welcome. Feel free to re-open this issue.
