### ISSUE TITLE
Implement save-artifacts to speed up composer

### ISSUE THREAD

**Issue by andrewklau** [sclorg/s2i-php-container#145]
Are there plans to implement the `save-artifacts` into the other containers so we can speed up build times?

**Comment by bparees** [comment]
we do have a card for it here and i think it's something we still want to do:
https://trello.com/c/h6XuTxmS/889-8-update-builder-images-to-support-incremental-techdebt-scl

but as these images are now owned by the SCL team, creating issues (or if the SCL team has a different RFE process they'd like to follow) makes sense.  @hhorak ?

**Comment by lucasnetau** [comment]
I've implemented save-artifacts for composer as a .s2i/bin script for some apps, I'm able to upload a pull request if wanted?
