### ISSUE TITLE
OpenShift Web server refreshes site back to original content

### ISSUE THREAD

**Issue by johnreytanquinco** [sclorg/s2i-php-container#148]
I am using OpenShift 1.5.1.alpha. I have a Drupal site installed in the server, integrates on a git repo. Everytime it creates a build on the server, site is redirected to its installation process.

I have noticed two things.
1. When I create dummy files and commit it to the repo, the files are permanently created on the server after the reinstallation.

2. When I create changes, install package from the server inside the Drupal root directory, everything is gone after it rebuilds/reinstall the site.

Also, the site installed is broken. I can only access the user and homepage with a no-theme-page. Looking on the browser console, I see that during the installation, site is not generating the CSS folder and needed files on it. All other pages or links is unaccessible. I check the permission of sites/ folder and changes everything to 777, I get no difference.

Thanks in advance!

-John Rey

**Comment by bparees** [comment]
for (1) git repo content gets added to the image as the image is built, so that will always be present.

for (2) it's not clear to me how you're introducing the changes, but if you are making changes to the running container then yes, those changes will be lost if either the container is restarted, or you build a new image.

If that's not what you're doing, i think we'll need more exact recreate steps.  @luciddreamz or @coreydaley, either of you have experience w/ drupal that might help here?

**Comment by coreydaley** [comment]
It's potentially the same issues that we had on V2.  You need to pick which way you want to make your changes:

- Run the drupal setup on OpenShift and then make all of your modifications through the Drupal admin.
- Do your setup locally and then commit your changed files to the repo so they don't get wiped out.

**Comment by johnreytanquinco** [comment]
Thanks @bparees and @coreydaley for your quick response. I really appreciate it.

Now, I get to understand how the server works. Since there's no way for me to execute Drush command(which I think would be first best step to configure and work on Drupal site), and that Drupal installation generates incomplete files and folders on the server that leads me to broken pages and URLs,

 - Does Drupal admin changes are saved on the image even if build is restarted?
 - Will my local changes commits on repo automatically reflects on the server or does it applied after another build?

I'm still new to this set up and I would really appreciate your help. I can't find Drupal related issues on google as I'm getting the openshift.redhat articles.

Thanks!

**Comment by coreydaley** [comment]
@johnreytanquinco Do you have any further questions/comments or should we go ahead and close this issue?
