### ISSUE TITLE
Opache memory consumption default too low for PHP7

### ISSUE THREAD

**Issue by lucasnetau** [sclorg/s2i-php-container#152]
The Zend Opcache memory consumption default of 16MB is too low in a PHP7 environment with interned string buffer set to 8MB (currently non-configurable in 10-opcache.ini).

This issue is described in https://bugs.php.net/bug.php?id=72720 

Why was 16MB chosen as the default for this container? The default set in PHP documentation for Opcache is 64MB and the scl-php70 package sets this at 128MB. Should the s2i-php container use this same default or another value? Small applications will happily run in 32MB allocated whereas Wordpress and Drupal will prefer 64 or 128.

Prior to #151, OpCache was allocated 128MB due to the run script not setting the container template correctly. Perhaps this value should be used as the default for the container to ensure BC.

**Comment by lucasnetau** [comment]
@remicollet What is a good default opcache memory size for PHP7?

**Comment by remicollet** [comment]
> @remicollet What is a good default opcache memory size for PHP7?

There is no good default.
Upstream default is 128M
But this is directly related to number and size of cached files.

**Comment by remicollet** [comment]
This have already been discussed, a too "low" value will imply a big loose of performance, as the cache will be continuously restarted on OOM error.

**Comment by lucasnetau** [comment]
Agreed.The default currently set it 16MB. The patch to fix the template file installation has led to this default being set.

If you agree, I'll raise a PR to set it to 128MB by default

**Comment by remicollet** [comment]
> If you agree, I'll raise a PR to set it to 128MB by default

seems fine, as it was the previous default when the configuration was badly installed (so, as you said, for BC)

**Comment by lucasnetau** [comment]
Thanks @remicollet, I've raised #153 to set the default to 128MB.

**Comment by omron93** [comment]
@lucasnetau  For BC - also for 5.6 is default 128MB?

**Comment by lucasnetau** [comment]
Yes, the packages rh-php56-php-opcache-5.6.25-1.el7.x86_64 and rh-php70-php-opcache-7.0.10-2.el7.x86_64 have 128MB as the default set in /etc/opt/rh/rh-php*/php.d/10-opcache.ini
