### ISSUE TITLE
Add mcrypt module

### ISSUE THREAD

**Issue by mguillem** [sclorg/s2i-php-container#161]
The installation of the mcrypt module per default or a documentation for it would be welcome.

**Comment by mguillem** [comment]
Perhaps may it help someone: I finally found way, creating own s2i builder based on `s2i-php-container`. Not so elegant but it works.
```
FROM centos/php-56-centos7:latest

USER root

# Install the additional PHP modules we need
RUN wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
	&& rpm -Uvh epel-release-latest-7.noarch.rpm \
	&& yum -y install rh-php56-php-mcrypt

USER 1001
```

**Comment by notroj** [comment]
We don't support mcrypt in RHSCL or SCLorg collections, so this is out of scope sorry.
