### ISSUE TITLE
How to use with OpenShift

### ISSUE THREAD

**Issue by magick93** [sclorg/s2i-php-container#168]
Hello

This repo description says:
>  intended for OpenShift and general usage

However the readme only gives examples of using directly with s2i and docker, which are standalone applications from OpenShift.

Also, the link to the OpenShift on the readme (https://docs.openshift.org/latest/using_images/s2i_images/php.html) also does not give instructions on how to use these with OpenShift, but instead with docker.

I\m interested in how I can use a template in OpenShift, which accepts a git url (containing php and/or composer.json) and create a php application image - from within OpenShift.

Any guidance on this is appreciated.

**Comment by bparees** [comment]
this sample repo will show you how to deploy a php app on openshift:
https://github.com/openshift/cakephp-ex

it also includes some sample templates if you want to deploy the app/repo via a template:
https://github.com/openshift/cakephp-ex/tree/master/openshift/templates
