### ISSUE TITLE
can't download composer installer

### ISSUE THREAD

**Issue by hoangweb** [sclorg/s2i-php-container#190]
i got this error, when build image:
`Found 'composer.json', installing dependencies using composer.phar...
Downloading https://getcomposer.org/installer, attempt 1/6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: getcomposer.org; Unknown error`

**Comment by omron93** [comment]
Please take a look in https://github.com/sclorg/s2i-php-container/pull/182

Sometime there is network problem when downloading `composer`. So there is 5 retries when it fails. Problem you reported is probably case of this network problem.

@hoangweb Does downloading of composer failed completely? Or other retries were successful?

**Comment by xrow** [comment]
This will fix it https://github.com/sclorg/s2i-php-container/issues/221

**Comment by phracek** [comment]
The issue is already fixed.
