### ISSUE TITLE
How to run script before starting httpd?

### ISSUE THREAD

**Issue by pr4xx** [sclorg/s2i-php-container#205]
When reading the docs, it states that you can create a `httpd-pre-init` folder which can contain bash scripts. Does this mean that these scripts will get executed before the httpd process is started in openshift or is this only meant for the s2i build process? If the latter is true, how do I execute some commands before starting this docker image?

I use a Laravel based php app and I need to execute "php artisan migrate" before starting httpd. How would I implement this?

**Comment by nsams** [comment]
I think you should do that using https://docs.openshift.com/container-platform/3.4/dev_guide/deployments/deployment_strategies.html#pod-based-lifecycle-hook

**Comment by pr4xx** [comment]
Thank you very much!
