### ISSUE TITLE
set sub directory as public root

### ISSUE THREAD

**Issue by guangrei** [sclorg/s2i-php-container#211]
hi, i have this structure in my git repository

- example (folder)
- public (folder)
- composer.json (file)

it's possible to set public folder as public web root?

**Comment by nsams** [comment]
you can do that using DOCUMENTROOT env var, see https://github.com/sclorg/s2i-php-container/blob/master/7.1/README.md#environment-variables

**Comment by mailinglists35** [comment]
@guangrei did you manage to set it up?
