### ISSUE TITLE
Adding a Script in "./httpd-pre-init" does not work as expected

### ISSUE THREAD

**Issue by dirkrydvan** [sclorg/s2i-php-container#213]
Hello,

at https://github.com/sclorg/s2i-php-container/blob/master/7.1/README.md is explained, how to extend the image with a Script that get started before httpd starts.

I add a skript in the httpd-pre-init subfolder directly at the git source root folder.
And there I placed a example.sh script.

I expected, that this script get started with the resulting container. But it wont be started.
The script exists inside the container:
```bash
bash# oc rsh containername
sh-4.2$ pwd
/opt/app-root/src
sh-4.2$ ls -al ./httpd-pre-init
total 12
drwxrwxr-x.  2 default root   46 May 24 10:26 .
drwxrwxr-x. 16 default root 4096 May 24 11:15 ..
-rw-rw-r--.  1 default root  509 May 24 10:26 example.sh
sh-4.2$
```
It seams, that the "run-httpd" script from the sclorg apache 2.4 container will not used/not exist:
```
sh-4.2$ find / -name "run-httpd" 2>/dev/null
sh-4.2$ find / -name "pre-init" 2>/dev/null
/usr/share/container-scripts/php/pre-init
sh-4.2$ ls -al /usr/share/container-scripts/php/pre-init
total 0
drwxr-xr-x. 2 root root  6 May  9 12:08 .
drwxr-xr-x. 6 root root 94 May  9 12:08 ..
sh-4.2$
```
Maybe some for pre-start or  is missing here to use function process_extending_files() from common.sh
https://github.com/sclorg/s2i-php-container/tree/master/7.0/root/usr/share/container-scripts/php

What is necessary, that this script get started once inside the container?

Many Thanks advance

**Comment by omron93** [comment]
Thanks for reporting this issue. There is inconsistency in what is in the code and what is in the readme.

README describes  `./httpd-cfg , ./httpd-pre-init , ./httpd-ssl` folders. But in code `./httpd-cfg , ./php-pre-start , ./httpd-ssl , ./php-post-assemble` folders are used.
@hhorak You introduced the change. Which naming we want use?

@dirkrydvan So hotfix for this issue is to use `php-pre-start` folder instead of `httpd-pre-init`. But be prepared that a resolution of this issue can change naming.

**Comment by hhorak** [comment]
@omron93 Yeah, naming is never easy :) my thinking behind this was to use the same entrypoint names where I'd expect the same content/use case for `httpd` and `php` container image -- that's the `httpd-ssl` a `httpd-cfg` case. However, my expectation for content/use case for `post-assemble` and `pre-start` entrypoints would be different in case of `php`, than in case of `httpd` container image; therefore different name. Anyway, my intention was what is in the code, the README is wrong in this case.
