### ISSUE TITLE
Composer via EPEL

### ISSUE THREAD

**Issue by xrow** [sclorg/s2i-php-container#221]
Hi,

I would like to add a feature to use the composer from epel instead of using it from assemble. Is that a better way of doing so? I am I allowed to send in a proposal/merge?

**Comment by omron93** [comment]
Hi,
problem with installing rpms (~ composer from EPEL) is that it can be done only in Dockerfile. And that would mean that composer from EPEL would be used in all cases. And I'm not sure if it's desired...

@remicollet What do you think?

**Comment by xrow** [comment]
I am always using composer from EPEL. It never let me down so far.

I feel having an composer install in assemble is a build penalty you would not want. Thanks for your feedback.

**Comment by remicollet** [comment]
Using EPEL is not possible, at least for RH images.

**Comment by xrow** [comment]
@remicollet is this a yes or a no?

**Comment by remicollet** [comment]
not possible, means NO

**Comment by xrow** [comment]
ok thanks for the feedback. please close. I think was thinking about a split logic for centos and rh which might be not desired.
