### ISSUE TITLE
PersistentVolume /opt/app-root/src

### ISSUE THREAD

**Issue by ElytschaOne** [sclorg/s2i-php-container#224]
> @akarasev no, i'm not saying that.  i'm saying that when you use an openshift volume, you're using the equivalent of a pre-existing directory with docker.
> I showed you how, when using docker, you can see the exact same behavior as what you are seeing in openshift.
> 
> My goal here is to have persistent /opt/app-root/src content.
> 
> **The only way you're going to get there is to mount the volume somewhere and have your run script for the image copy the content you want to the mounted location, and then run the application from that location.**

So how we can achieve this? Do we need to fork the repo and modificate the run btw. assemble scripts to our needs? If thats true that wouldn't be a good option for prod environments, we would like to use the original source repos for that and no forks, its an additional bunch of work to maintain forked repos eg. to keep em in track with the upstream.

Problem: we have a php application which should have persistant files, like configs, so that after each recreate or new deployment the config files which store access to the database have to be still present.

**Comment by nsams** [comment]
Configs should be part of the deployment configuration, for example as environment variables.

**Comment by omron93** [comment]
> So how we can achieve this? Do we need to fork the repo and modificate the run btw. assemble scripts to our needs? If thats true that wouldn't be a good option for prod environments, we would like to use the original source repos for that and no forks, its an additional bunch of work to maintain forked repos eg. to keep em in track with the upstream.

Not knowing problem, sorry.
But generally, to provide custom `run` or `assemble` script you don't have to fork the repo. You can place it in `.s2i/bin/` folder in you app source for s2i build (see [1]). In some cases is also possible to source original script in it and only to add something.

[1] https://github.com/openshift/source-to-image/blob/master/docs/runtime_image.md#assemble-runtime-script-requirements
