### ISSUE TITLE
support for php-fpm using rhel7

### ISSUE THREAD

**Issue by dakkusingh** [sclorg/s2i-php-container#228]
Hi all, 
Is there any interest in getting this project to support php-fpm with rhel7? Or, is there another project that is doing this already?

**Comment by atierant** [comment]
Hi,
I have seen another project doing this :
https://github.com/sclorg/s2i-php-container/compare/master...CountPickering:master

**Comment by patrick-tavares** [comment]
I forked this project some time ago to add fpm support: [https://github.com/patrick-tavares/s2i-php-container/tree/master/7.1-fpm](url). It's currently based on 7.1 and needs an update to 7.2/7.3 but I've been successfully running a production app (in conjunction with nginx containers) for a while. At some point I'll submit a PR here.

**Comment by phracek** [comment]
PHP-FPM support is planned only for RHEL9. The older RHEL versions are not supported like RHEL7 and RHEL8.
