### ISSUE TITLE
Allow tuning php.ini's memory_limit

### ISSUE THREAD

**Issue by ibotty** [sclorg/s2i-php-container#230]
It would be great to be able to set `memory_limit`: https://github.com/sclorg/s2i-php-container/blob/master/7.1/root/opt/app-root/etc/php.ini.template#L389

I can provide a patch, but what's the preferred environment variable name?  I prefer `PHP_MEMORY_LIMIT`.

Cheers

**Comment by omron93** [comment]
@remicollet ?

**Comment by remicollet** [comment]
As 128M is really big, make sense

**Comment by ibotty** [comment]
Well, for the one app I am currently deploying it's too small :(.

**Comment by omron93** [comment]
@ibotty :-D Anyway, PR is really welcomed. `PHP_MEMORY_LIMIT` sound fine. Thanks.
