### ISSUE TITLE
Proper way to upgrade PostgreSQL tools.

### ISSUE THREAD

**Issue by pittar** [sclorg/s2i-php-container#242]
Hello!

I hope this question isn't too basic, but I'm having trouble figuring out the proper way to upgrade the Postgres libraries in this image.  I'm running Drupal with this s2i image using a PostgreSQL 9.6 database.  Everything works fine, but Drupal has some built-in backup utils that are failing because the version of `pg_dump` that is included is 9.2.  I need to upgrade this to 9.6.

I've created by Dockerfile, used it to create a custom s2i image, and used this new image to build Drupal:
```
# FROM registry.access.redhat.com/rhscl/php-72-rhel7
FROM centos/php-72-centos7

USER root

ENV POSTGRESQL_VERSION=9.6

# Update the image with the latest packages (recommended)
RUN yum update -y; yum clean all

# Install Apache Web Server
RUN yum install -y rh-postgresql96-postgresql-contrib rh-postgresql95-postgresql-server graphviz; yum clean all

USER 1001
```

When I `rsh` into a fresh Drupal pod, I can see that the `POSTGRESQL_VERSION` env var is set to 9.6, but if I run `pg_dump --version`, it still reports as 9.2.

I'm sure I'm missing something simple.  Can you please advise?

Thanks.

**Comment by gripenk** [comment]
you should issue `scl enable rh-postgresql96 bash`  or `source  /opt/rh/rh-php72/enable`

ref: https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql96/

**Comment by pittar** [comment]
Thanks for the advice.

I ended up forking the repo, then added "rh-postgresql96" to the `INSTALL_PKGS` list, then updated the `SCL_ENABLED` to be:
```
SCL_ENABLED="rh-php72 rh-postgresql96"
```
Worked like a charm.
