### ISSUE TITLE
Support for php 7.3

### ISSUE THREAD

**Issue by hbenmansour** [sclorg/s2i-php-container#249]
Hi, 

Is php 7.3 going to be supported sometimes in 2019 - 2020 ? 

Many thanks
Hamza

**Comment by CountPickering** [comment]
PHP 7.3 has not made it to Software Collections yet.  You can browse here for some packages: https://www.softwarecollections.org/en/scls/user/rhscl/

Here is the official documentation for Software Collections 3.2 where php72 support was added: https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.2_release_notes/chap-rhscl#sect-RHSCL-Changes-php

There is a Software Collections 3.3 but a new php package is not included.

That said ..... you could create your own using Remi's repo to install the 7.3 packages.  You will need to modify the dockerfile and update package names and the file paths.
https://blog.remirepo.net/post/2019/05/30/PHP-version-7.1.30-7.2.19-and-7.3.6

**Comment by phracek** [comment]
The PHP-7.3 is already supported by PR #261
