### ISSUE TITLE
Feature-Request: Allow Importing root CA through configuration

### ISSUE THREAD

**Issue by fhoutr01** [sclorg/s2i-php-container#256]
Hello,

I was trying to import a certificate into the container and noticed it wasn't a configurable option. Is it possible to add this? It's possible in different S2I images such as the dotnet runtime S2I.

I'll give some background on my use-case and my current "workaround" which seems to work well enough for my use case.

#Tools
- Gitlab for pipelining
- OpenShift 3.11 cluster
- https://www.keycloak.org/docs/latest/securing_apps/index.html#forward-signing-proxy

#Situation
We have a RedHat SSO cluster running which we use for authentication between applications, as well as for user authentication in the application. To avoid too many issues with the token authentication/refreshing we had a look at keycloak-gatekeeper to resolve this cross-cutting concern.

Image two applications:

Application A is a JSON REST API which only accepts bearer tokens.
Application B is an application that needs to connect to application A.

Application B is a pod that has (1) the main application container and (2) a keycloak-gatekeeper sidecar container.

When we do a request to Application A from application B the sidecar is the proxy between the two that adds in the necessary headers. This means the proxy is playing man in the middle and signs the certificates with it's own certificate. That means unverified connections between the application (B) and the proxy. I'd rather avoid this, even though they are both within the same pod.

So I generated my own root certificate to sign with and had the gatekeeper used that certificate instead ( it has parameters for it ). Then I needed to import this root certificate into my application container so it would trust the connection. Unfortunately there are no options to have the container automatically pick it up based on a configuration value. And that's what I would like to achieve. An option that would take all certificates in a certain folder ( the configuration value ) and combine them with the ( default ) certificates that are already present inside the container.

#My workaround

In our pipeline ( gitlab ) I do the following:

[Build Stage]

    - Generate a new root certificate
    - Download the latest certificate bundle from the curl website
    - Combine them in a new file
    - Have OpenShift do the S2I with an archive of the code ( including my combined .pem file )
    - Create an artifact of the .pem and .key file

Sample pipeline code

    - openssl req -x509 -nodes -days 12000 -newkey rsa:4096 -keyout ca.key -out ca.pem -subj "<subject here>"
    - curl -O https://curl.haxx.se/ca/cacert.pem
    - cat cacert.pem > cert-bundle.pem
    - printf "\n#self-signed certificate\n" >> cert-bundle.pem
    - cat ca.pem >> cert-bundle.pem
    - printf "\n"
    - tar -zcf app.tar.gz .s2i/ public/ httpd-cfg/ cert-bundle.pem
    - oc login <your-cluster> --token=<your-token>
    - oc start-build <build-config> --from-archive=app.tar.gz -n <build-project> -w -F

[Deploy Stage]

Per environment I deploy the image to:

    - Create a new secret on that environment  containing my .pem and .key
    - Execute the deployment

Set the following environment variable:

    SSL_CERT_FILE=/opt/app-root/src/cert-bundle.pem
This is the path I mount the combined certificate bundle to. This variable tells cURL to use that .pem file for validating certificates.

Set the following apache configuration in httpd-cfg/ ( this is picked up by your scripts ).

    <VirtualHost *:8080>
        #other configuration here
        php_admin_value curl.cainfo /opt/app-root/src/cert-bundle.pem
    </VirtualHost>

This changes the pem file used by curl in the PHP Runtime. I haven't tested this extensively, so I'm not even sure if it works with other libraries who might not depend on cURL.

So it's not perfect. Unfortunately I don't see another way to do this right now and this was the "cleanest" solution I could come up with on short notice. Most libraries have a way to specify the ca file, but it'd be nice if it would just work by reading the system default.

I can check if I can create a pull request for this after my holidays. Is this a feature you're willing to add to the image?

# Other use-cases
Another use-case I can imagine is if you use a cloud service ( e.g.: AWS ) you need to import their certificate if you want encrypted connections to their database.

Thanks!

**Comment by fhoutr01** [comment]
Update: What I'm asking for is the same as the DOTNET_SSL_DIRS in the dotnetcore-runtime image on https://docs.openshift.com/online/using_images/s2i_images/dot_net_core.html

**Comment by phracek** [comment]
Thank you for taking the time to report this issue to us. We appreciate the feedback and use reports such as this one to guide our efforts at improving our products. That being said, we have been not able to get to this issue for a long time, so rather closing it to make it clear we don't see it be addressed soon.

If this issue is critical or in any way time sensitive, please raise a ticket through the regular Red Hat support channels to ensure it receives the proper attention and prioritization to assure a timely resolution.

For information on how to contact the Red Hat production support team, please visit: https://access.redhat.com/support
