### ISSUE TITLE
How to update image stream?

### ISSUE THREAD

**Issue by ryannix123** [sclorg/s2i-php-container#276]
Hello,

How can update the OKD image stream to PHP 7.2?

Thanks!

**Comment by phracek** [comment]
Thanks for the question.

As far as I know, image streams are maintained by OpenShift team, @bparees .
Can you please help @ryannix123 ? Thank you.

**Comment by bparees** [comment]
@ryannix123 what version of openshift are you using?

in OCP4 the imagestreams are provided by the samples operator:
https://github.com/openshift/cluster-samples-operator/tree/master/tmp/build/assets/operator/ocp-x86_64

and the samples operator pulls from:
https://github.com/openshift/library/

You get new samples by updating your OCP cluster to a newer version (Which includes an update to the samples operator).

If even the latest samples operator does not include the imagestream/tag you are looking for, you can just create/install the imagestream yourself.

`oc apply -f https://raw.githubusercontent.com/openshift/library/master/official/php/imagestreams/php-rhel7.json -n openshift`

should do it for you.

in ocp3, the imagestreams are created at install time and updated during upgrades..again if you want something that's not there you can either upgrade to a newer version of openshift that provides it, or you can install the imagestream yourself via the command above.

**Comment by ryannix123** [comment]
Thank you for the quick reply!

I'm using OKD 3.11 built from Grant's demo. I'm actually doing a demo of Openshift for colleagues at my university.

The command you provided work with one a warning: 
```
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
imagestream.image.openshift.io/php configured
```

And while the image did show up in the web UI, when I went to deploy an app I received the following error:
`Imagestreamtags.image.openshift.io "php:7.2" not found`

**Comment by bparees** [comment]
@ryannix123 i'm guessing the import failed, can you share the output of `oc get is php -o yaml -n openshift`?  Most likely you need to provide a valid pull credential for registry.redhat.io in the openshift namespace and then reimport (via oc import-image):
https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#private-registries

Alternatively you can edit the imagestream to import from "registry.access.redhat.com" which does not currently require credentials but should have all the same images.

You can safely ignore the warning you got on apply.

**Comment by ryannix123** [comment]
@bparees I think you're spot on. I didn't have proper access to the internal Redhat registry. I'll try your suggestion of editing the imagestream to point at the public registry. Thanks again!
```

      lastTransitionTime: 2019-12-10T18:30:25Z
      message: 'Internal error occurred: Get https://registry.redhat.io/v2/rhscl/php-72-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer Portal
        credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication'
```

**Comment by ryannix123** [comment]
Changing the registry address to the public one worked. Thanks again, @bparees @phracek!
