### ISSUE TITLE
Publish Fedora Images to the Fedora Container Registry

### ISSUE THREAD

**Issue by cragr** [sclorg/s2i-php-container#298]
For [OKD 4 ](https://github.com/openshift/okd) we are needing to pull current images from the [Fedora Container Registry](https://registry.fedoraproject.org/) but images from the Dockerfile.fedora are not available.  Is it possible to have the maintainers of sclorg/s2i-php-container push the Fedora containers to the Fedora registry?  The current image naming convention "php-73-centos7" could be "php-73-fedora31" as it uses the f31 s2i-base image.  

https://github.com/openshift/okd/issues/167

**Comment by phracek** [comment]
This issue is obsolete. We are pushing regularly images to Fedora quay.io namespace. See: https://quay.io/organization/fedora
