### ISSUE TITLE
Why isn't INSTALL_PKG a build arg ?

### ISSUE THREAD

**Issue by larueli** [sclorg/s2i-php-container#302]
Hello !

In every of your Dockerfile, you have more or less the following lines :
```
RUN yum install -y centos-release-scl && \
    INSTALL_PKGS="rh-php73 rh-php73-php ... httpd24-mod_ssl" && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS --nogpgcheck && \
    rpm -V $INSTALL_PKGS && \
    yum -y clean all --enablerepo='*'
```

I think it would be a good idea to replace the precedent lines with : 
```
ARG INSTALL_PKGS="rh-php73 rh-php73-php ... httpd24-mod_ssl"
ENV INSTALL_PKGS=$INSTALL_PKGS

RUN yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS --nogpgcheck && \
    rpm -V $INSTALL_PKGS && \
    yum -y clean all --enablerepo='*'
```

**It would allow anyone to customize packages in their own s2i source image** without having to fork the repo, like in this case #242 

I can submit a Pull Request if you want. I'm opening an issue first in order to check if I missed something @hhorak.

Thanks

**Comment by phracek** [comment]
@larueli Can you please submit a Pull Request to this issue?
