### ISSUE TITLE
s2i-php-container 7.4 Quay.io failing

### ISSUE THREAD

**Issue by xrow** [sclorg/s2i-php-container#330]
I noticed already for a couple months that https://quay.io/repository/centos7/php-74-centos7 does not exist. I guess internal mebers are aware. Nevertheless I thought I should create a ticket for this for people to subscribe once this is fixed.

**Comment by phracek** [comment]
Hi @xrow . That's true. It looks like we do not have and repositories for CentOS7 yet. The file https://github.com/sclorg/s2i-php-container/blob/master/7.4/.exclude-centos7 is present and therefore it failing
But it should not be marked as failing but rather "not done yet".

@khardix Do you know when RPMs will be available for CentOS7 so we can build PHP-7.4 container for CentOS7?

**Comment by khardix** [comment]
@phracek Is there an rh-php74 SCL? I'm happy to rebuild it once it exists, but so far the only PHP-7.4 RPMs I was able to found are all from EL8…

**Comment by pkubatrh** [comment]
Afaik there is no 7.4 rhscl, so there wont be any centos7 image builds for it.

**Comment by pkubatrh** [comment]
You can however use the UBI8-based image: https://catalog.redhat.com/software/containers/ubi8/php-74/5f521244e05bbcd88f128b63?gti-tabs=unauthenticated
