### ISSUE TITLE
Environment variables are being ignored by the php engine

### ISSUE THREAD

**Issue by olstjos** [sclorg/s2i-php-container#403]
Our application is crashing because we rely on environment variables for the 
DB_HOST, 
DB_PASSWORD, 
DB_USER
 and other important environment variables for AWS that we cannot push into source control with our app build.

This regression appears to be related to changing from mod_php to php_fpm

I found a Red Hat support article but I have to ask colleagues to open it because I do not have the red hat subscription, someone else does.
https://access.redhat.com/solutions/6972818

Ubi9/php-81 image change from mod_php to php_fpm drops environment variables.

So I found this :

https://github.com/docker-library/php/issues/74

Suggests to add **clear_env = no** to the conf for php-fpm

Ok so I'm attempting to fix it as follows:

```
diff --git a/Dockerfile b/Dockerfile
index 148dbef..a13ca34 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -21,6 +21,9 @@ RUN curl -s -o $COMPOSER_FILE https://getcomposer.org/installer && \
 
 COPY / /opt/app-root/src
 
+# Ensure that environment variables are maintained, add it to an existing [www] pool.
+RUN echo "clear_env = no" >> /etc/php-fpm.d/www.conf
+
RUN chmod -R ug=u+wX /etc/php.d && \
     chmod ug=u+wx /etc/php.ini && \
     chmod 777 /var/log && \

```

**Comment by olstjos** [comment]
this fix works, the fix should likely be incorporated into the s2i-php-container

**Comment by pkubatrh** [comment]
This was reported for ubi8/php-80 as well: https://bugzilla.redhat.com/show_bug.cgi?id=2120351

PHP experts say that this change of behavior is made by upstream and is security related and as such I am not sure if removing it should get into the images by default - we tend to follow what upstream thinks is best configuration. Feel free to add a comment to the Bugzilla bug however if you disagree, it's likely there most of the discussion will happen if we see more folks hitting this issue.

**Comment by olstjos** [comment]
We're using environment variables for "security reasons" justified as follows:

Our application needs secrets stored in open shift that we cannot commit into source control.

Our application does not permit unprivileged users from executing random php code.

**Comment by paulbadcock** [comment]
I also really dislike this default. As a compromise can  a pattern to generate the www.conf like the php.ini https://github.com/sclorg/s2i-php-container/blob/master/8.1/s2i/bin/run#L34 ?

This will give the user who flags the environment variable the ability for the clean to be turned off. Also this will allow future features in the fpm like fpm debug logs to be controlled via environment variables vs a whole custom docker file we are running now to work around this per #360
