### ISSUE TITLE
need php 7.0

### ISSUE THREAD

**Issue by gautamkrishnar** [sclorg/s2i-php-container#80]
I need php 7.0 for deploying an Application. How can i do that?
If there is a documentation to create a docker PHP i will be happy to create a PR here.

**Comment by gautamkrishnar** [comment]
Can you guys help me on this:
i actually need php 5.5.9 its not available in openshift 
https://github.com/gautamkrishnar/koel-openshift-quickstart

**Comment by bparees** [comment]
It looks like you're trying to use openshift v2.  This repository is for the PHP image for openshift v3.

V3 offers PHP 5.5 and PHP 5.6.

V2 is unlikely to introduce new PHP version support at this point in its lifecycle.

**Comment by jderusse** [comment]
Can you please reopen this issue?
Openshift v3 should provide the last version of PHP (7.0) which provided better performances (see how baddoo saved million dollars https://techblog.badoo.com/blog/2016/03/14/how-badoo-saved-one-million-dollars-switching-to-php7/)

**Comment by bparees** [comment]
@hhorak is php7 anywhere on the SCL roadmap?

**Comment by mfojtik** [comment]
There is an article about how to install PHP7 for centos7: 

https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-centos-7

I believe this can be used to change the provided Dockerfile and install PHP7.

**Comment by hhorak** [comment]
PHP7 is being considered for inclusion in some of the next RHSCL releases, it didn't make it to RHSCL 2.2 for capacity reasons unfortunately.

**Comment by Nicofuma** [comment]
Do you have any ETA for the arrival of PHP7 in RHSCL and the s2i images?
Thanks

**Comment by spinolacastro** [comment]
Hello @Nicofuma, check this out [https://github.com/getupcloud/sti-php/tree/master/7.0](url)

**Comment by hhorak** [comment]
We're not able to be much specific, since it is not a public info, but we're considering it for 2.3 release.

**Comment by jkramarz** [comment]
Hi all, I've re-done @spinolacastro work, but using @remicollet SCLs from remi-safe instead of remi-php70 to follow convention. As I suppose, it'd be impossible to merge these changes because it's not using SoftwareCollections (which does not include PHP 7.0 at this time) and does not support RHEL7 (as I can't run tests without subscription), but some of you may find it helpful:
https://github.com/jkramarz/s2i-php-container/tree/php7
Branch contains files required for building PHP 7.0 and PHP 7.1 CentOS7 s2i containers.

**Comment by remicollet** [comment]
RHSCL 2.3beta is released with rh-php70 packages.

**Comment by hhorak** [comment]
PHP 7.0 is now available. Closing this issue.

**Comment by gautamkrishnar** [comment]
👍  finally.... 😄
